### ISSUE TITLE
InvalidArgumentError: input_1:0 is both fed and fetched. This error when I run the code for VisualBackprop

### ISSUE THREAD

**Issue by mzmmoazam** [experiencor/deep-viz-keras#8]
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-9-102f4108b70a> in <module>()
      2 visual_bprop = VisualBackprop(model)
      3 
----> 4 mask = visual_bprop.get_mask(x[0])
      5 show_image(mask, ax=plt.subplot('121'), title='visual backprop')
      6 

6 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/errors_impl.py in __exit__(self, type_arg, value_arg, traceback_arg)
    526             None, None,
    527             compat.as_text(c_api.TF_Message(self.status.status)),
--> 528             c_api.TF_GetCode(self.status.status))
    529     # Delete the underlying status object from memory otherwise it stays alive
    530     # as there is a reference to status from this from the traceback due to

InvalidArgumentError: input_1:0 is both fed and fetched.

**Comment by Eurus-Holmes** [comment]
I have the same error...

**Comment by mzmmoazam** [comment]
@Eurus-Holmes I have fixed the error in my pull repository. Can check it out.
